### ISSUE TITLE
Image File Request for testing ekfoa

### ISSUE THREAD

**Issue by kongan** [gnvo/ekfoa#1]
Thank you for providing this job.

Would you please provide me Image File(ardrone/wall/img or ardrone/held_indoors/img) for testing ekfoa?

Thank you in advance for your help!

**Comment by nv-pipo** [comment]
Hi!
Thanks! and sorry I lost the images used for testing. Change of laptop.
It should work with any set of images of a continuous video of a monocular camera.
Cheers,
N
